package Alura.ForumHub.domain.curso;

public enum Categoria {

    CIENCIA_COMPUTACAO,
    ENGENHARIA_SOFTWARE,
    REDES_COMPUTADORES,
    SEGURANCA_INFORMACAO,
    INTELIGENCIA_ARTIFICIAL,
    DESENVOLVIMENTO_MOBILE,
    DESENVOLVIMENTO_DE_SISTEMAS

}
